openapi: 3.0.3
info:
  title: Swagger Peerly
  description: |-
    Peer to peer appreciations
  version: 1.0.11
servers:
  - url: http://localhost:33001/
tags:
  - name: Core Values
    description: Core Value cruds

paths:

  /core_values/{coreValueId}:
    put:
      tags:
        - Core Values
      summary: Update an existing core value
      description: Update an existing core value by Id
      operationId: updateCoreValue
      parameters:
        - name: coreValueId
          in: path
          description: ID of corevalue
          required: true
          schema:
            type: integer
            format: int64
          example: 32
        - in: header
          name: Accept-Version
          required: true
          description: Defines the media type and version of the API endpoint
          schema:
            enum:
              - 'application/vnd.peerly.v1'
            type: string
      requestBody:
        description: Update an existing core value in the organisation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCoreValues'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input data
        '404':
          description: Core value id not found
        '500':
          description: Internal server error
          
    get:
      tags:
        - Core Values
      summary: Finds corevalue by id
      description: get a corevalue corevalue id
      operationId: get a corevalue by id
      parameters:
        - name: coreValueId
          in: path
          description: ID of corevalue
          required: true
          schema:
            type: integer
            format: int64
          example: 1
        - in: header
          name: Accept-Version
          required: true
          description: Defines the media type and version of the API endpoint
          schema:
            enum:
              - 'application/vnd.peerly.v1'
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetCoreValuesResp'          
        '404':
          description: Invalid core value id
                  
  /core_values:
    post:
      tags:
        - Core Values
      summary: Add a new core value
      description: Add a new core value
      operationId: addCoreValue
      parameters:
        - in: header
          name: Accept-Version
          required: true
          description: Defines the media type and version of the API endpoint
          schema:
            enum:
              - 'application/vnd.peerly.v1'
            type: string
      requestBody:
        description: Create a new core value
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCoreValues'
        required: true
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCoreValuesResp'          

        '400':
          description: Invalid input
        '500' :
          description: Internal server error

    get:
      tags:
        - Core Values
      summary: List all corevalues of the organisation
      description: List all the core values of the specified organisation
      operationId: listCoreValues
      parameters:
        - in: header
          name: Accept-Version
          required: true
          description: Defines the media type and version of the API endpoint
          schema:
            enum:
              - 'application/vnd.peerly.v1'
            type: string

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListCoreValuesResp'          
        '500':
          description: Internal server error

components:
  schemas:
    
    UpdateCoreValues:
      type: object
      properties:
        name:
          type: string
          example: Updated core value
        description:
          type: string
          example: updated description
    
    CreateCoreValues:
      type: object
      properties:
        name:
          type: string
          example: Updated core value
        description:
          type: string
          example: updated description
        parent_core_value_id:
          type: integer
          format: int64
          example: 1
          
    CreateCoreValuesResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        parent_core_value_id:
          type: integer
          format: int64
          
    GetCoreValuesResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        parent_core_value_id:
          type: integer
          format: int64
          
    ListCoreValuesResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        parent_core_value_id:
          type: integer
          format: int64
       